#!/bin/sh
set -eu
url="http://127.0.0.1:8080/realms/zoen/.well-known/openid-configuration"
until python3 -c 'import sys, urllib.request; urllib.request.urlopen(sys.argv[1], timeout=2)' "$url" >/dev/null 2>&1; do
  sleep 1
done
exec "$@"
