#!/bin/sh
set -eu
mkdir -p /data/restate
exec env -i \
  PATH=/usr/local/bin:/usr/bin:/bin \
  RESTATE_ADMIN__BIND_ADDRESS=127.0.0.1:9070 \
  RESTATE_INGRESS__BIND_ADDRESS=127.0.0.1:9071 \
  RUST_LOG="${RUST_LOG:-info}" \
  /usr/local/bin/restate-server --base-dir /data/restate
