avoid-breaking-exported-api = false
too-many-arguments-threshold = 9
allowed-duplicate-crates = [
  "arrayvec",
  "base64",
  "bitflags",
  "block-buffer",
  "const-oid",
  "cpufeatures",
  "crypto-common",
  "digest",
  "embedded-io",
  "foldhash",
  "getrandom",
  "hashbrown",
  "hmac",
  "indexmap",
  "md-5",
  "object",
  "petgraph",
  "phf_shared",
  "r-efi",
  "rand",
  "rand_chacha",
  "rand_core",
  "redox_syscall",
  "reqwest",
  "schemars",
  "sha2",
  "syn",
  "unicode-width",
  "webpki-roots",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
