sonar.projectKey=EnzoTironi_OS
sonar.organization=enzotironi
sonar.sources=.
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/gen/**,docs/research/2026-09-02-openbb-ontology/**
sonar.javascript.lcov.reportPaths=lcov.info
