/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdaptiveSurfaceRouteImport } from './routes/api.adaptive-surface'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApproveControlRefRouteImport } from './routes/approve.$controlRef'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as PacksIndexRouteImport } from './routes/packs.index'
import { Route as PacksDigestRouteImport } from './routes/packs.$digest'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as ApiOnboardingBeginGrantRouteImport } from './routes/api.onboarding.begin-grant'
import { Route as ApiOnboardingCaptureRouteImport } from './routes/api.onboarding.capture'
import { Route as ApiOnboardingResumeRouteImport } from './routes/api.onboarding.resume'
import { Route as ApiPacksOpenRouteImport } from './routes/api.packs.open'
import { Route as ApiPacksSearchRouteImport } from './routes/api.packs.search'
import { Route as ApproveAuthCallbackRouteImport } from './routes/approve.auth.callback'
import { Route as OnboardingAuthCallbackRouteImport } from './routes/onboarding.auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptiveSurfaceRoute = ApiAdaptiveSurfaceRouteImport.update({
  id: '/api/adaptive-surface',
  path: '/api/adaptive-surface',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveControlRefRoute = ApproveControlRefRouteImport.update({
  id: '/approve/$controlRef',
  path: '/approve/$controlRef',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksDigestRoute = PacksDigestRouteImport.update({
  id: '/packs/$digest',
  path: '/packs/$digest',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingBeginGrantRoute = ApiOnboardingBeginGrantRouteImport.update({
  id: '/api/onboarding/begin-grant',
  path: '/api/onboarding/begin-grant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCaptureRoute = ApiOnboardingCaptureRouteImport.update({
  id: '/api/onboarding/capture',
  path: '/api/onboarding/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingResumeRoute = ApiOnboardingResumeRouteImport.update({
  id: '/api/onboarding/resume',
  path: '/api/onboarding/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksOpenRoute = ApiPacksOpenRouteImport.update({
  id: '/api/packs/open',
  path: '/api/packs/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacksSearchRoute = ApiPacksSearchRouteImport.update({
  id: '/api/packs/search',
  path: '/api/packs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveAuthCallbackRoute = ApproveAuthCallbackRouteImport.update({
  id: '/approve/auth/callback',
  path: '/approve/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAuthCallbackRoute = OnboardingAuthCallbackRouteImport.update({
  id: '/onboarding/auth/callback',
  path: '/onboarding/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/approve/$controlRef': typeof ApproveControlRefRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/packs/$digest': typeof PacksDigestRoute
  '/rpc/$': typeof RpcSplatRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/api/onboarding/begin-grant': typeof ApiOnboardingBeginGrantRoute
  '/api/onboarding/capture': typeof ApiOnboardingCaptureRoute
  '/api/onboarding/resume': typeof ApiOnboardingResumeRoute
  '/api/packs/open': typeof ApiPacksOpenRoute
  '/api/packs/search': typeof ApiPacksSearchRoute
  '/approve/auth/callback': typeof ApproveAuthCallbackRoute
  '/onboarding/auth/callback': typeof OnboardingAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/approve/$controlRef': typeof ApproveControlRefRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/packs/$digest': typeof PacksDigestRoute
  '/rpc/$': typeof RpcSplatRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/packs': typeof PacksIndexRoute
  '/api/onboarding/begin-grant': typeof ApiOnboardingBeginGrantRoute
  '/api/onboarding/capture': typeof ApiOnboardingCaptureRoute
  '/api/onboarding/resume': typeof ApiOnboardingResumeRoute
  '/api/packs/open': typeof ApiPacksOpenRoute
  '/api/packs/search': typeof ApiPacksSearchRoute
  '/approve/auth/callback': typeof ApproveAuthCallbackRoute
  '/onboarding/auth/callback': typeof OnboardingAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/approve/$controlRef': typeof ApproveControlRefRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/packs/$digest': typeof PacksDigestRoute
  '/rpc/$': typeof RpcSplatRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/api/onboarding/begin-grant': typeof ApiOnboardingBeginGrantRoute
  '/api/onboarding/capture': typeof ApiOnboardingCaptureRoute
  '/api/onboarding/resume': typeof ApiOnboardingResumeRoute
  '/api/packs/open': typeof ApiPacksOpenRoute
  '/api/packs/search': typeof ApiPacksSearchRoute
  '/approve/auth/callback': typeof ApproveAuthCallbackRoute
  '/onboarding/auth/callback': typeof OnboardingAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/adaptive-surface'
    | '/api/config'
    | '/approve/$controlRef'
    | '/auth/callback'
    | '/packs/$digest'
    | '/rpc/$'
    | '/onboarding/'
    | '/packs/'
    | '/api/onboarding/begin-grant'
    | '/api/onboarding/capture'
    | '/api/onboarding/resume'
    | '/api/packs/open'
    | '/api/packs/search'
    | '/approve/auth/callback'
    | '/onboarding/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/adaptive-surface'
    | '/api/config'
    | '/approve/$controlRef'
    | '/auth/callback'
    | '/packs/$digest'
    | '/rpc/$'
    | '/onboarding'
    | '/packs'
    | '/api/onboarding/begin-grant'
    | '/api/onboarding/capture'
    | '/api/onboarding/resume'
    | '/api/packs/open'
    | '/api/packs/search'
    | '/approve/auth/callback'
    | '/onboarding/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/api/adaptive-surface'
    | '/api/config'
    | '/approve/$controlRef'
    | '/auth/callback'
    | '/packs/$digest'
    | '/rpc/$'
    | '/onboarding/'
    | '/packs/'
    | '/api/onboarding/begin-grant'
    | '/api/onboarding/capture'
    | '/api/onboarding/resume'
    | '/api/packs/open'
    | '/api/packs/search'
    | '/approve/auth/callback'
    | '/onboarding/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdaptiveSurfaceRoute: typeof ApiAdaptiveSurfaceRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApproveControlRefRoute: typeof ApproveControlRefRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PacksDigestRoute: typeof PacksDigestRoute
  RpcSplatRoute: typeof RpcSplatRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PacksIndexRoute: typeof PacksIndexRoute
  ApiOnboardingBeginGrantRoute: typeof ApiOnboardingBeginGrantRoute
  ApiOnboardingCaptureRoute: typeof ApiOnboardingCaptureRoute
  ApiOnboardingResumeRoute: typeof ApiOnboardingResumeRoute
  ApiPacksOpenRoute: typeof ApiPacksOpenRoute
  ApiPacksSearchRoute: typeof ApiPacksSearchRoute
  ApproveAuthCallbackRoute: typeof ApproveAuthCallbackRoute
  OnboardingAuthCallbackRoute: typeof OnboardingAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adaptive-surface': {
      id: '/api/adaptive-surface'
      path: '/api/adaptive-surface'
      fullPath: '/api/adaptive-surface'
      preLoaderRoute: typeof ApiAdaptiveSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$controlRef': {
      id: '/approve/$controlRef'
      path: '/approve/$controlRef'
      fullPath: '/approve/$controlRef'
      preLoaderRoute: typeof ApproveControlRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$digest': {
      id: '/packs/$digest'
      path: '/packs/$digest'
      fullPath: '/packs/$digest'
      preLoaderRoute: typeof PacksDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/begin-grant': {
      id: '/api/onboarding/begin-grant'
      path: '/api/onboarding/begin-grant'
      fullPath: '/api/onboarding/begin-grant'
      preLoaderRoute: typeof ApiOnboardingBeginGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/capture': {
      id: '/api/onboarding/capture'
      path: '/api/onboarding/capture'
      fullPath: '/api/onboarding/capture'
      preLoaderRoute: typeof ApiOnboardingCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/resume': {
      id: '/api/onboarding/resume'
      path: '/api/onboarding/resume'
      fullPath: '/api/onboarding/resume'
      preLoaderRoute: typeof ApiOnboardingResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/open': {
      id: '/api/packs/open'
      path: '/api/packs/open'
      fullPath: '/api/packs/open'
      preLoaderRoute: typeof ApiPacksOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/packs/search': {
      id: '/api/packs/search'
      path: '/api/packs/search'
      fullPath: '/api/packs/search'
      preLoaderRoute: typeof ApiPacksSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/auth/callback': {
      id: '/approve/auth/callback'
      path: '/approve/auth/callback'
      fullPath: '/approve/auth/callback'
      preLoaderRoute: typeof ApproveAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/auth/callback': {
      id: '/onboarding/auth/callback'
      path: '/onboarding/auth/callback'
      fullPath: '/onboarding/auth/callback'
      preLoaderRoute: typeof OnboardingAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdaptiveSurfaceRoute: ApiAdaptiveSurfaceRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApproveControlRefRoute: ApproveControlRefRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PacksDigestRoute: PacksDigestRoute,
  RpcSplatRoute: RpcSplatRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PacksIndexRoute: PacksIndexRoute,
  ApiOnboardingBeginGrantRoute: ApiOnboardingBeginGrantRoute,
  ApiOnboardingCaptureRoute: ApiOnboardingCaptureRoute,
  ApiOnboardingResumeRoute: ApiOnboardingResumeRoute,
  ApiPacksOpenRoute: ApiPacksOpenRoute,
  ApiPacksSearchRoute: ApiPacksSearchRoute,
  ApproveAuthCallbackRoute: ApproveAuthCallbackRoute,
  OnboardingAuthCallbackRoute: OnboardingAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
