/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdaptiveSurfaceRouteImport } from './routes/api.adaptive-surface'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdaptiveSurfaceRoute = ApiAdaptiveSurfaceRouteImport.update({
  id: '/api/adaptive-surface',
  path: '/api/adaptive-surface',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/rpc/$': typeof RpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/rpc/$': typeof RpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/adaptive-surface': typeof ApiAdaptiveSurfaceRoute
  '/api/config': typeof ApiConfigRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/rpc/$': typeof RpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/adaptive-surface' | '/api/config' | '/auth/callback' | '/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/api/adaptive-surface' | '/api/config' | '/auth/callback' | '/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/api/adaptive-surface'
    | '/api/config'
    | '/auth/callback'
    | '/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdaptiveSurfaceRoute: typeof ApiAdaptiveSurfaceRoute
  ApiConfigRoute: typeof ApiConfigRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RpcSplatRoute: typeof RpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/adaptive-surface': {
      id: '/api/adaptive-surface'
      path: '/api/adaptive-surface'
      fullPath: '/api/adaptive-surface'
      preLoaderRoute: typeof ApiAdaptiveSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdaptiveSurfaceRoute: ApiAdaptiveSurfaceRoute,
  ApiConfigRoute: ApiConfigRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RpcSplatRoute: RpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
