FROM node:22.18.0-bookworm-slim

WORKDIR /app
COPY . .
RUN npm ci \
    && npm run build \
    && npm cache clean --force \
    && chown -R node:node /app

ENV NODE_ENV=production
USER node
CMD ["node", "dist/packages/effect-worker/src/worker.js"]
