CREATE ROLE zoen_app
    LOGIN
    PASSWORD 'zoen_app'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT;

GRANT CONNECT ON DATABASE zoen TO zoen_app;
GRANT ALL ON SCHEMA public TO zoen_app;
ALTER DATABASE zoen OWNER TO zoen_app;
