import { readFile, writeFile } from "node:fs/promises";

const jsonPath = "docs/product/roadmap.json";
const mdPath = "docs/product/roadmap.md";
const htmlPath = "docs/product/roadmap.html";

const STATUS_LABEL = {
  have: "HAVE",
  "dont-have": "DON'T HAVE",
  "stub-on-main": "STUB ON MAIN",
  "in-flight": "IN FLIGHT",
  parked: "PARKED",
  harness: "HARNESS",
};

const STATUS_BLURB = {
  have: "On main. Real implementation. This is product.",
  "dont-have": "Not product. Restore issue is the row. Code, if any, lives on the backup branch.",
  "stub-on-main": "On main today only as a fake or stub. Leaves main. Backup already holds the files. Restore issue is the row.",
  "in-flight": "Fail-closed work in an open PR. Do not duplicate.",
  parked: "Intent exists. Blocked on a vendor, a credential, or a named issue. Do not advertise.",
  harness: "Named test double next to a real implementation. Not a product path. Allowed only when labeled and not exported as product.",
};

const data = JSON.parse(await readFile(jsonPath, "utf8"));
const md = renderMarkdown(data);
const html = renderHtml(data);

if (process.argv.includes("--check")) {
  const currentMd = await readFile(mdPath, "utf8");
  const currentHtml = await readFile(htmlPath, "utf8");
  if (currentMd !== md || currentHtml !== html) {
    throw new Error(
      `${mdPath} or ${htmlPath} is stale. Run node scripts/render-roadmap.mjs`,
    );
  }
} else {
  await writeFile(mdPath, md);
  await writeFile(htmlPath, html);
}

function issueLink(n) {
  return `https://github.com/EnzoTironi/OS/issues/${n}`;
}

function prLink(n) {
  return `https://github.com/EnzoTironi/OS/pull/${n}`;
}

function mdIssue(n) {
  return n == null ? "—" : `[#${n}](${issueLink(n)})`;
}

function mdPrs(prs) {
  if (!Array.isArray(prs) || prs.length === 0) {
    return "—";
  }
  return prs.map((n) => `[#${n}](${prLink(n)})`).join(", ");
}

function count(status) {
  return data.rows.filter((row) => row.status === status).length;
}

function renderMarkdown(doc) {
  const groups = Object.keys(STATUS_LABEL);
  const sections = groups
    .map((status) => {
      const rows = doc.rows.filter((row) => row.status === status);
      if (rows.length === 0) {
        return "";
      }
      const body = rows
        .map(
          (row) =>
            `| \`${row.id}\` | ${row.plane} | ${row.name} | ${escapeMd(row.proof)} | ${mdIssue(row.issue)} |`,
        )
        .join("\n");
      return `## ${STATUS_LABEL[status]}

${STATUS_BLURB[status]}

| id | plane | name | proof | issue |
| --- | --- | --- | --- | ---: |
${body}
`;
    })
    .filter(Boolean)
    .join("\n");

  const next = doc.next
    .map((item) => {
      const prs = mdPrs(item.pr);
      return `| ${item.order} | ${mdIssue(item.issue)} | ${prs} | ${item.title} | ${escapeMd(item.note)} |`;
    })
    .join("\n");

  const forbidden = doc.forbidden.map((line) => `- ${line}`).join("\n");

  return `# Zoen OS roadmap

Generated from \`docs/product/roadmap.json\`. Do not edit this file. Run \`node scripts/render-roadmap.mjs\`.

Parent issue [#${doc.parentIssue}](${issueLink(doc.parentIssue)}).
Backup [\`${doc.backup.branch}\`](${doc.backup.url}) at \`${doc.backup.sha}\`.

## Law

${doc.law}

## Counts

| HAVE | DON'T HAVE | STUB ON MAIN | IN FLIGHT | PARKED | HARNESS |
| ---: | ---: | ---: | ---: | ---: | ---: |
| ${count("have")} | ${count("dont-have")} | ${count("stub-on-main")} | ${count("in-flight")} | ${count("parked")} | ${count("harness")} |

## Do next

| order | issue | PR | title | note |
| ---: | ---: | --- | --- | --- |
${next}

## Gates

- \`${doc.gates.verify}\`
- \`${doc.gates.verifyV1}\`
- \`${doc.gates.verifyActivation}\`

${doc.gates.note}

## Forbidden

${forbidden}

${sections}
Open the visual board at [docs/product/roadmap.html](./roadmap.html).
`;
}

function escapeMd(value) {
  return String(value).replaceAll("|", "\\|");
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function renderHtml(doc) {
  const cards = Object.keys(STATUS_LABEL)
    .map(
      (status) => `<button class="stat" data-filter="${status}" type="button">
  <span class="stat-count">${count(status)}</span>
  <span class="stat-label">${STATUS_LABEL[status]}</span>
</button>`,
    )
    .join("\n");

  const next = doc.next
    .map((item) => {
      const prs =
        Array.isArray(item.pr) && item.pr.length > 0
          ? item.pr
              .map(
                (n) =>
                  `<a href="${prLink(n)}">PR #${n}</a>`,
              )
              .join(" ")
          : "";
      return `<li>
  <span class="order">${item.order}</span>
  <div>
    <a href="${issueLink(item.issue)}">#${item.issue}</a>
    ${prs}
    <strong>${escapeHtml(item.title)}</strong>
    <p>${escapeHtml(item.note)}</p>
  </div>
</li>`;
    })
    .join("\n");

  const tables = Object.keys(STATUS_LABEL)
    .map((status) => {
      const rows = doc.rows.filter((row) => row.status === status);
      if (rows.length === 0) {
        return "";
      }
      const body = rows
        .map((row) => {
          const issue =
            row.issue == null
              ? "—"
              : `<a href="${issueLink(row.issue)}">#${row.issue}</a>`;
          const backup =
            Array.isArray(row.backup) && row.backup.length > 0
              ? `<div class="path">${row.backup.map(escapeHtml).join("<br>")}</div>`
              : row.path
                ? `<div class="path">${escapeHtml(row.path)}</div>`
                : "";
          const blocker = row.blocker
            ? `<div class="blocker">Blocked on ${escapeHtml(row.blocker)}</div>`
            : "";
          return `<tr data-status="${status}">
  <td><code>${escapeHtml(row.id)}</code></td>
  <td>${escapeHtml(row.plane)}</td>
  <td>
    <div class="name">${escapeHtml(row.name)}</div>
    ${backup}
    ${blocker}
  </td>
  <td>${escapeHtml(row.proof)}</td>
  <td>${issue}</td>
</tr>`;
        })
        .join("\n");
      return `<section class="group" data-group="${status}">
  <h2>${STATUS_LABEL[status]}</h2>
  <p class="blurb">${STATUS_BLURB[status]}</p>
  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>plane</th>
        <th>capability</th>
        <th>proof</th>
        <th>issue</th>
      </tr>
    </thead>
    <tbody>
${body}
    </tbody>
  </table>
</section>`;
    })
    .join("\n");

  const forbidden = doc.forbidden
    .map((line) => `<li>${escapeHtml(line)}</li>`)
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zoen OS roadmap</title>
  <style>
    :root {
      --bg: #0e1014;
      --panel: #171a21;
      --ink: #e8eadf;
      --muted: #9aa194;
      --line: #2a2f38;
      --have: #7dcf83;
      --dont: #e07070;
      --stub: #f0b429;
      --flight: #6cb3f3;
      --parked: #9aa194;
      --harness: #c792ea;
    }
    * { box-sizing: border-box; }
    html, body {
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font: 16px/1.45 ui-sans-serif, system-ui, -apple-system, sans-serif;
    }
    a { color: var(--flight); }
    header {
      padding: 2rem 1.5rem 1rem;
      max-width: 1100px;
      margin: 0 auto;
    }
    h1 { font-size: 1.75rem; margin: 0 0 0.5rem; font-weight: 650; }
    h2 { font-size: 1.1rem; margin: 0 0 0.4rem; letter-spacing: 0.04em; }
    .law {
      max-width: 70ch;
      color: var(--muted);
      margin: 0 0 1.25rem;
    }
    .meta { color: var(--muted); font-size: 0.9rem; }
    .meta code { color: var(--ink); }
    .stats {
      display: grid;
      grid-template-columns: repeat(6, minmax(0, 1fr));
      gap: 0.5rem;
      max-width: 1100px;
      margin: 0 auto 1.5rem;
      padding: 0 1.5rem;
    }
    .stat {
      background: var(--panel);
      border: 1px solid var(--line);
      color: var(--ink);
      padding: 0.85rem 0.7rem;
      text-align: left;
      cursor: pointer;
    }
    .stat[data-filter="have"] { border-top: 3px solid var(--have); }
    .stat[data-filter="dont-have"] { border-top: 3px solid var(--dont); }
    .stat[data-filter="stub-on-main"] { border-top: 3px solid var(--stub); }
    .stat[data-filter="in-flight"] { border-top: 3px solid var(--flight); }
    .stat[data-filter="parked"] { border-top: 3px solid var(--parked); }
    .stat[data-filter="harness"] { border-top: 3px solid var(--harness); }
    .stat.active { outline: 1px solid var(--ink); }
    .stat-count { display: block; font-size: 1.6rem; font-weight: 700; }
    .stat-label { display: block; font-size: 0.72rem; color: var(--muted); margin-top: 0.2rem; }
    main { max-width: 1100px; margin: 0 auto; padding: 0 1.5rem 4rem; }
    .next {
      background: var(--panel);
      border: 1px solid var(--line);
      padding: 1rem 1.2rem;
      margin-bottom: 2rem;
    }
    .next ol { list-style: none; padding: 0; margin: 0; }
    .next li { display: flex; gap: 0.8rem; padding: 0.7rem 0; border-top: 1px solid var(--line); }
    .next li:first-child { border-top: 0; }
    .order {
      flex: 0 0 1.6rem;
      height: 1.6rem;
      text-align: center;
      background: #111;
      border: 1px solid var(--line);
      font-size: 0.8rem;
      line-height: 1.6rem;
    }
    .next p { margin: 0.2rem 0 0; color: var(--muted); font-size: 0.9rem; }
    table { width: 100%; border-collapse: collapse; margin: 0.6rem 0 2rem; font-size: 0.92rem; }
    th, td { border-bottom: 1px solid var(--line); padding: 0.55rem 0.4rem; vertical-align: top; text-align: left; }
    th { color: var(--muted); font-weight: 600; font-size: 0.75rem; letter-spacing: 0.04em; text-transform: uppercase; }
    .name { font-weight: 600; }
    .path, .blocker { color: var(--muted); font-size: 0.8rem; margin-top: 0.2rem; }
    .blocker { color: var(--stub); }
    .blurb { color: var(--muted); max-width: 70ch; margin: 0 0 0.6rem; }
    .forbidden { color: var(--dont); }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85em; }
    @media (max-width: 800px) {
      .stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    }
  </style>
</head>
<body>
  <header>
    <h1>Zoen OS. What exists.</h1>
    <p class="law">${escapeHtml(doc.law)}</p>
    <p class="meta">
      Parent <a href="${issueLink(doc.parentIssue)}">#${doc.parentIssue}</a>.
      Backup <a href="${escapeHtml(doc.backup.url)}"><code>${escapeHtml(doc.backup.branch)}</code></a>
      at <code>${escapeHtml(doc.backup.sha)}</code>.
      Source <code>docs/product/roadmap.json</code>.
    </p>
  </header>
  <div class="stats">
${cards}
  </div>
  <main>
    <section class="next">
      <h2>Do next</h2>
      <ol>
${next}
      </ol>
    </section>
    <section>
      <h2>Gates</h2>
      <p class="blurb">${escapeHtml(doc.gates.note)}</p>
      <ul>
        <li><code>${escapeHtml(doc.gates.verify)}</code></li>
        <li><code>${escapeHtml(doc.gates.verifyV1)}</code></li>
        <li><code>${escapeHtml(doc.gates.verifyActivation)}</code></li>
      </ul>
    </section>
    <section>
      <h2>Forbidden</h2>
      <ul class="forbidden">
${forbidden}
      </ul>
    </section>
${tables}
  </main>
  <script>
    const buttons = [...document.querySelectorAll(".stat")];
    let current = "all";
    for (const button of buttons) {
      button.addEventListener("click", () => {
        const status = button.getAttribute("data-filter");
        current = current === status ? "all" : status;
        for (const b of buttons) {
          b.classList.toggle("active", b.getAttribute("data-filter") === current);
        }
        for (const group of document.querySelectorAll(".group")) {
          group.hidden = current !== "all" && group.getAttribute("data-group") !== current;
        }
      });
    }
  </script>
</body>
</html>
`;
}
