{{- if .Values.reference.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: restate
  labels:
    {{- include "zoen.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: restate
  ports:
    - name: node
      port: 5122
      targetPort: node
    - name: ingress
      port: 8080
      targetPort: ingress
      nodePort: {{ .Values.restate.ingressNodePort }}
    - name: admin
      port: 9070
      targetPort: admin
      nodePort: {{ .Values.restate.adminNodePort }}
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: restate
  labels:
    {{- include "zoen.labels" . | nindent 4 }}
spec:
  serviceName: restate
  replicas: {{ .Values.restate.topology.referenceReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: restate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: restate
        {{- include "zoen.labels" . | nindent 8 }}
    spec:
      containers:
        - name: restate
          image: {{ .Values.images.restate }}
          env:
            - name: RESTATE_ADVERTISED_ADDRESS
              value: http://restate:5122
            - name: RESTATE_AUTO_PROVISION
              value: "true"
            - name: RESTATE_FORCE_NODE_ID
              value: "1"
            - name: RESTATE_NODE_NAME
              value: restate
          ports:
            - name: node
              containerPort: 5122
            - name: ingress
              containerPort: 8080
            - name: admin
              containerPort: 9070
          readinessProbe:
            httpGet:
              path: /health
              port: admin
            initialDelaySeconds: 2
            periodSeconds: 2
          volumeMounts:
            - name: data
              mountPath: /restate-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.restate.storage }}
{{- end }}
